document.addEventListener("DOMContentLoaded", function () {
    const switcher = document.getElementById("language-switcher");
    let currentLang = localStorage.getItem("lang") || "es";

    const translations = {
        en: {
            "site-title": "WILD-CATCH COLOMBIA",
            "about-us": "About Us",
            "products": "Products",
            "events": "Events",
            "trips": "Trips",
            "contact-us": "Contact Us",
            "home-heading": "Responsible, Fresh & Sustainable Fishing",
            "home-text": "WILD-CATCH FISH MARKET is dedicated to leading the fishing industry sustainably, prioritizing ocean conservation and social equity in fishing communities.",
            "see-products": "See Our Products",
            "place-order": "Place Your First Order",
            "kg-fish": "Kilograms of Fish",
            "restaurants-reached": "Restaurants Reached",
            "collaborators": "Collaborators",
            "footer-text": "&copy; 2025 Wild Catch Fish Market. All rights reserved.",
            "about-title": "About Us",
            "testimonies": "Trips",
            "contact": "Contact Us",
            "timeline-2014": "Our first time in Bahía Solano, Colombia.",
            "timeline-2017": "The first logistics test was carried out, bringing fresh fish from Bahía Solano.",
            "timeline-2020": "During the pandemic, the second test was carried out, bringing fish and seafood.",
            "timeline-2022": "The WILD-CATCH COLOMBIA group was founded, carrying out multiple fishing trips throughout the year.",
            "timeline-2023": "The group founded WILD-CATCH FISH MARKET, beginning with the distribution of fish and seafood in Antioquia, Colombia.",
            "timeline-2024": "National distribution began, and forecasted goals were achieved.",
            "timeline-2025": "Growth continued, and a collection center was established in Bahía Solano.",
            "purpose": "Purpose",
            "purpose-text": "Our purpose at WILD-CATCH Fish Market is to lead the fishing industry sustainably, prioritizing ocean conservation and social equity in fishing communities.",
            "mission": "Mission",
            "mission-text": "Our mission is to create opportunities in Bahía Solano to contribute to its economic and social development.",
            "vision": "Vision",
            "vision-text": "To be leaders in sustainable fishing and expand our community worldwide.",
            "event-title": "Tuna Ronqueo - Wild Catch Fish Market",
            "what-is-ronqueo": "What is Tuna Ronqueo?",
            "ronqueo-description": "Ronqueo is the traditional art of tuna cutting, a technique passed down through generations.",
            "ronqueo-usage": "This practice allows the use of every part of the tuna, ensuring maximum yield and offering high-quality products.",
            "restaurant-collaboration": "Collaboration with the Best Restaurants",
            "collaboration-text": "We partner with top fine-dining restaurants to bring live ronqueo events to exclusive gatherings.",
            "service-offering": "We provide a full service, ensuring quality, freshness, and an unparalleled culinary spectacle.",
            "trips-title": "Trips - Wild Catch Fish Market",
            "trips-heading": "WILD-CATCH Tourism",
            "about-us": "About Us",
            "products": "Products",
            "events": "Events",
            "contact-us": "Contact Us",
            "trips-info-heading": "Bahía Solano: A Paradise for Fishing and Eco-Tourism",
            "trips-info-text": "More than just a destination, Bahía Solano is a perfect blend of fishing, adventure, and culture. Its waters, rich in biodiversity, offer spectacular catches, challenging anglers with large species. But the experience goes beyond that: this Pacific gem allows visitors to connect with nature, explore virgin beaches, and enjoy local cuisine and culture. <strong>Experience the best of Bahía Solano with WILD-CATCH, where every expedition combines excitement, landscapes, and authenticity.</strong>",
            "whatsapp-booking": "Book your trip via WhatsApp",
            "trips-gallery-title": "TRIPS",
            "footer-text": "&copy; 2025 Wild Catch Fish Market. All rights reserved.",
            "contact-title": "Contact Us",
            "contact-us": "Contact Us",
            "whatsapp": "WHATSAPP",
            "email": "Email:",
            "footer-text": "&copy; 2025 Wild Catch Fish Market. All rights reserved.",
            "products-title": "Products",
            "products": "Products",
            "order-here": "Order Here",
            "about-us": "About Us",
            "events": "Events",
            "trips": "Trips",
            "contact": "Contact Us",
            "fish": "Fish",
            "seafood": "Seafood",
            "tuna": "Yellowfin Tuna",
            "dorado": "Mahi-Mahi",
            "sierra": "Wahoo",
            "bravo": "Bravo",
            "cherna": "Grouper",
            "merluza": "Hake",
            "pargo": "Red Snapper",
            "pargop": "Red Silver Snapper",
            "berrugate": "Berrugate",
            "robalo": "Snook",
            "sardinata": "Sardinata",
            "corvina": "Croaker",
            "octopus": "Octopus",
            "prawns": "Prawns",
            "shrimp": "Shrimp",
            "crab-claws": "Crab Claws",
            "lobster-tail": "Lobster Tail",
            "footer-text": "&copy; 2025 Wild Catch Fish Market. All rights reserved."
        },
        es: {
            "site-title": "WILD-CATCH COLOMBIA",
            "about-us": "Quiénes Somos",
            "products": "Productos",
            "events": "Eventos",
            "trips": "Viajes",
            "contact-us": "Contáctanos",
            "home-heading": "Pesca responsable, fresca & sostenible.",
            "home-text": "WILD-CATCH FISH MARKET está dedicado a liderar la industria pesquera de manera sostenible.",
            "see-products": "Conoce Nuestros Productos",
            "place-order": "Realiza tu Primer Pedido",
            "kg-fish": "Kilogramos de pescado",
            "restaurants-reached": "Restaurantes Llegados",
            "collaborators": "Colaboradores",
            "footer-text": "&copy; 2025 Wild Catch Fish Market. Todos los derechos reservados.",
            "about-title": "Sobre Nosotros",
            "testimonies": "Viajes",
            "contact": "Contáctanos",
            "timeline-2014": "Nuestra primera vez en Bahía Solano, Colombia.",
            "timeline-2017": "Se hizo el primer ensayo de logística trayendo pesca fresca de Bahía Solano.",
            "timeline-2020": "En la pandemia se hizo el segundo ensayo trayendo pescados y mariscos.",
            "timeline-2022": "Se fundó el grupo WILD-CATCH COLOMBIA realizando múltiples viajes de pesca.",
            "timeline-2023": "El grupo fundó WILD-CATCH FISH MARKET, empezando con distribución de pescados y mariscos.",
            "timeline-2024": "Empezó la distribución a nivel nacional y se lograron alcanzar las metas.",
            "timeline-2025": "Continuó el crecimiento y se creó el centro de acopio en Bahía Solano.",
            "purpose": "Propósito",
            "purpose-text": "Nuestro propósito en WILD-CATCH Fish Market es liderar la industria de la pesca de manera sostenible.",
            "mission": "Misión",
            "mission-text": "Nuestra misión es generar oportunidades en Bahía Solano para contribuir a su desarrollo.",
            "vision": "Visión",
            "vision-text": "Ser líderes en la pesca sostenible y expandir nuestra comunidad alrededor del mundo.",
            "event-title": "Ronqueo de Atún - Wild Catch Fish Market",
            "what-is-ronqueo": "¿Qué es el Ronqueo de Atún?",
            "ronqueo-description": "El ronqueo es el arte tradicional de despiece del atún.",
            "ronqueo-usage": "Esta práctica permite aprovechar cada parte del atún, asegurando el máximo rendimiento.",
            "restaurant-collaboration": "Colaboración con los Mejores Restaurantes",
            "collaboration-text": "Nos asociamos con los mejores restaurantes de alta cocina para llevar el ronqueo en vivo.",
            "service-offering": "Ofrecemos un servicio integral, asegurando calidad, frescura y un espectáculo culinario.",
            "trips-title": "Recuerdos - Wild Catch Fish Market",
            "trips-heading": "Turismo WILD-CATCH",
            "about-us": "Quiénes Somos",
            "products": "Productos",
            "events": "Eventos",
            "contact-us": "Contáctanos",
            "trips-info-heading": "Bahía Solano: Un Paraíso para la pesca y el eco turismo.",
            "trips-info-text": "Más que un destino, Bahía Solano es una combinación perfecta de pesca, aventura y cultura. Sus aguas, ricas en biodiversidad, ofrecen capturas espectaculares, desafiando a los pescadores con especies de gran tamaño. Pero la experiencia va más allá: este rincón del Pacífico permite conectar con la naturaleza, explorar playas vírgenes y disfrutar la gastronomía y cultura local. <strong>Vive lo mejor de Bahía Solano con WILD-CATCH, donde cada expedición combina emoción, paisajes y autenticidad.</strong>",
            "whatsapp-booking": "Haz tu reserva vía WhatsApp",
            "trips-gallery-title": "VIAJES",
            "footer-text": "&copy; 2025 Wild Catch Fish Market. Todos los derechos reservados.",
            "contact-title": "Contáctanos - Wild Catch Fish Market",
            "contact-us": "Contáctanos",
            "whatsapp": "WHATSAPP",
            "email": "Correo Electrónico:",
            "footer-text": "&copy; 2025 Wild Catch Fish Market. Todos los derechos reservados.",
            "products-title": "Nuestros Productos - Wild Catch Fish Market",
            "products": "Productos",
            "order-here": "Pide aquí",
            "about-us": "Quiénes Somos",
            "events": "Eventos",
            "trips": "Viajes",
            "contact": "Contáctanos",
            "fish": "Pescados",
            "seafood": "Mariscos",
            "tuna": "Atún Aleta Amarilla",
            "dorado": "Dorado",
            "sierra": "Sierra Wahoo",
            "bravo": "Bravo",
            "cherna": "Cherna",
            "merluza": "Merluza",
            "pargo": "Pargo Rojo",
            "berrugate": "Berrugate",
            "robalo": "Robalo",
            "sardinata": "Sardinata",
            "corvina": "Corvina",
            "octopus": "Pulpo",
            "prawns": "Langostinos",
            "shrimp": "Gambas",
            "crab-claws": "Muelas de Cangrejo",
            "lobster-tail": "Cola de Langosta",
            "footer-text": "&copy; 2025 Wild Catch Fish Market. Todos los derechos reservados."
        }
    };

    function updateLanguage(lang) {
        document.querySelectorAll("[data-translate]").forEach(el => {
            const key = el.getAttribute("data-translate");
            if (translations[lang] && translations[lang][key]) {
                el.textContent = translations[lang][key];
            }
        });

        if (switcher) {
            switcher.textContent = lang === "es" ? "English" : "Español";
        }
        localStorage.setItem("lang", lang);
    }

    if (switcher) {
        switcher.addEventListener("click", function () {
            currentLang = currentLang === "es" ? "en" : "es";
            updateLanguage(currentLang);
        });
    }

    updateLanguage(currentLang);
});


